export declare var farsiStrings: {
    groupButton: string;
    ungroupButton: string;
    selectButton: string;
    hideColumn: string;
    showColumn: string;
    moveToDetail: string;
    showAsColumn: string;
    visualizer_text: string;
    visualizer_wordcloud: string;
    chartType_bar: string;
    chartType_pie: string;
    chartType_scatter: string;
    chartType_gauge: string;
    chartType_bullet: string;
    hideButton: string;
    resetFilter: string;
    clearButton: string;
    addElement: string;
};
