export declare class SurveyJSON5 {
    static positionName: string;
    private static escapee;
    private static ws;
    private endAt;
    private at;
    private ch;
    private text;
    private parseType;
    constructor(parseType?: number);
    parse(source: any, reviver?: any, startFrom?: number, endAt?: number): any;
    private error;
    private next;
    private peek;
    private chartAt;
    private identifier;
    private number;
    private string;
    private inlineComment;
    private blockComment;
    private comment;
    private white;
    private word;
    private array;
    private object;
    private value;
    private replacer;
    private indentStr;
    private objStack;
    stringify(obj: any, replacer?: any, space?: any): any;
    private getIndent;
    private getReplacedValueOrUndefined;
    private isWordChar;
    private isWordStart;
    private isWord;
    private isArray;
    private isDate;
    private isNaN;
    private checkForCircular;
    private makeIndent;
    private static cx;
    private static escapable;
    private static meta;
    private escapeString;
    private internalStringify;
}
