export declare var localization: {
    currentLocaleValue: string;
    defaultLocaleValue: string;
    locales: {
        [index: string]: any;
    };
    localeNames: {
        [index: string]: any;
    };
    supportedLocales: any[];
    currentLocale: string;
    defaultLocale: string;
    getString: (strName: string) => any;
    getLocales: () => Array<string>;
};
export declare var surveyStrings: {
    groupButton: string;
    ungroupButton: string;
    selectButton: string;
    hideColumn: string;
    showColumn: string;
    makePrivateColumn: string;
    makePublicColumn: string;
    moveToDetail: string;
    showAsColumn: string;
    filterPlaceholder: string;
    removeRows: string;
    showLabel: string;
    entriesLabel: string;
    visualizer_text: string;
    visualizer_wordcloud: string;
    visualizer_histogram: string;
    visualizer_number: string;
    visualizer_choices: string;
    visualizer_selectBase: string;
    chartType_bar: string;
    chartType_vbar: string;
    chartType_stackedbar: string;
    chartType_doughnut: string;
    chartType_pie: string;
    chartType_scatter: string;
    chartType_gauge: string;
    chartType_bullet: string;
    hideButton: string;
    makePrivateButton: string;
    makePublicButton: string;
    showButton: string;
    filter: string;
    resetFilter: string;
    changeLocale: string;
    en: string;
    fr: string;
    ru: string;
    de: string;
    clearButton: string;
    addElement: string;
    defaultOrder: string;
    ascOrder: string;
    descOrder: string;
    showMinorColumns: string;
    otherCommentTitle: string;
    showPercentages: string;
    hidePercentages: string;
    pdfDownloadCaption: string;
    xlsxDownloadCaption: string;
    csvDownloadCaption: string;
    saveDiagramAsPNG: string;
    hideEmptyAnswers: string;
    showEmptyAnswers: string;
    "topNValueText-1": string;
    topNValueText5: string;
    topNValueText10: string;
    topNValueText20: string;
    hideMissingAnswers: string;
    showMissingAnswers: string;
    missingAnswersLabel: string;
    noVisualizerForQuestion: string;
    noResults: string;
    showPerValues: string;
    showPerColumns: string;
    answer: string;
    correctAnswer: string;
    percent: string;
    responses: string;
};
